### ISSUE TITLE
block controller input when xbox2mouse is enabled

### ISSUE THREAD

**Issue by adamjimenez** [adamjimenez/XBox2Mouse#16]

**Comment by adamjimenez** [comment]
http://www.autohotkey.com/board/topic/28703-is-there-a-way-to-block-input-from-360-controller/

**Comment by Danielet10** [comment]
This would be very nice, because sometimes you need to disable that, for example, in Steam o Kodi, where you have two different signals sent to the program, and the program gets a bit crazy (well, who really gets crazy is you hehe).

**Comment by adamjimenez** [comment]
when this happens I disable X2M using LB+RB+Left Stick press

Apparently this is impossible:
http://www.autohotkey.com/board/topic/34802-how-to-disable-joystick-powup-and-powdown/

**Comment by adamjimenez** [comment]
wontfix
