### ISSUE TITLE
Virtual Keyboard

### ISSUE THREAD

**Issue by Danielet10** [adamjimenez/XBox2Mouse#24]
I know that's not essential, but in the original xboxmouse, when you press Y, the VK appears, and when you press Y again, the VK disappears. With this one, you have to close manually VK, what is not embarrassing, but I think is more confortable just to press both mods + Dpad down again, isn't it? 
Thanks for everything, regards!

**Comment by adamjimenez** [comment]
Good point, I will fix this.

**Comment by Danielet10** [comment]
Great!!
