### ISSUE TITLE
Image of mouse enabled/disabled

### ISSUE THREAD

**Issue by Danielet10** [adamjimenez/XBox2Mouse#25]
Hi! 
I'd like to say one thing, that is not essential like the problem with the keyboard and I don't know if it could be fixed.
When I am at the desktop, or navigating with the browser, and I enable/disable the mouse mode, the image appears without any problem, but when I am in a fullscreen app, like Steam, Kodi, or any video game, the image just doesn't seem to appear, could it be this fixed?
When I used the original xboxmouse 1.5, the message text "Mouse mode, enabled/disabled" appeared without depending when app that it was running.

**Comment by adamjimenez** [comment]
I stopped the image from showing when an app is fullscreen. This is because I had an issue where it would pull the game out of fullscreen. I could change it back to a tooltip when in Fullscreen mode.
