### ISSUE TITLE
XBOX 360 Wireless Controller is auto scrolling down

### ISSUE THREAD

**Issue by awak3** [adamjimenez/XBox2Mouse#27]
Tested on three devices. Two origina wireless Xbox 360 controllers (not the "for PC Versions") are scrolling constantly down, scrolling up just works with the "up" key, which scrolls a bit up but immediately the scroll down process starts.
The Original Xbox 360 Controller for PC (cablebound) has not the issue.

I think it has something to do with the trigger buttons, tested "XboxMouse" and it had not the issue.

Would be really happy if this gets fixed.

**Comment by adamjimenez** [comment]
Thanks for the report. I notice it happen when the wireless controller goes to sleep - it's as if the trigger is being held down. It started to happen when I upgraded autohotkey. I will have a look.

**Comment by adamjimenez** [comment]
This is fixed
